version: "3"

services:
  db:
    container_name: postgres
    restart: always
    image: postgres:alpine
    environment:
      POSTGRES_USER: DB_USER
      POSTGRES_PASSWORD: DB_PASSWORD
    expose:
      - 5432
    volumes:
      - ./db_data/:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass REDIS_PASSWORD
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis_data:/data
    expose:
      - 6379

  nest:
    container_name: nest
    restart: always
    build:
      context: ./nest_js
      dockerfile: Dockerfile
    links:
      - db
      - redis
    expose:
      - 3001
    volumes:
      - ./public:/public
    environment:
      DB_HOST: db # 数据库地址
      DB_USER: DB_USER # 数据库用户
      DB_PASSWORD: DB_PASSWORD # 数据库的用户密码
      COOKIE_SECRET: COOKIE_SECRET # cookies密钥
      REDIS_URL: redis://:REDIS_PASSWORD@redis:6379/0 # Redis的连接地址

  nuxt:
    container_name: nuxt
    restart: always
    build:
      context: ./nuxt_js
      dockerfile: Dockerfile
    expose:
      - 3000

  nginx:
    container_name: nginx
    restart: always
    image: nginx:alpine
    volumes:
      - ./config/nginx/product.nginx:/etc/nginx/conf.d/product.nginx # 配置文件
      - ./public:/public # 静态文件
    ports:
      - 80:80
      - 443:443
    links:
      - nest
      - nuxt
    command: nginx -g 'daemon off;' -c /etc/nginx/conf.d/product.nginx


