version: "3"

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: 账号名(数据库名)
      POSTGRES_PASSWORD: 密码
    expose:
      - 5432
    volumes:
      - ./db_data/:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    command: redis-server --requirepass 密码
    expose:
      - 6379

  nest:
    build:
      context: ./nest_js
      dockerfile: Dockerfile
    links:
      - db
      - redis
    expose:
      - 3000
    volumes:
      - ./public:/public

  nuxt:
    build:
      context: ./nuxt_js
      dockerfile: Dockerfile
    expose:
      - 3000

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx_config/product.nginx:/etc/nginx/conf.d/product.nginx # 配置文件
      - ./public:/public # 静态文件
    ports:
      - 80:80
    links:
      - nest
      - nuxt
    restart: always
    command: nginx -g 'daemon off;' -c /etc/nginx/conf.d/product.nginx


