version: "3"

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: DB_USER
      POSTGRES_PASSWORD: DB_PASSWORD
    expose:
      - 5432
    volumes:
      - ./db_data/:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    command: redis-server --requirepass REDIS_PASSWORD
    expose:
      - 6379

  nest:
    build:
      context: ./nest_js
      dockerfile: Dockerfile
    links:
      - db
      - redis
    expose:
      - 3000
    volumes:
      - ./public:/public
    environment:
      - COOKIE_SECRET=COOKIE_SECRET # cookies密钥
      - DB_HOST=db # 数据库地址
      - DB_USER=DB_USER # 数据库用户
      - DB_PASSWORD=DB_PASSWORD #数据库的用户密码
      - REDIS_URL='redis://:REDIS_PASSWORD@redis:6379/0' #Redis的连接地址

  nuxt:
    build:
      context: ./nuxt_js
      dockerfile: Dockerfile
    expose:
      - 3000

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx_config/product.nginx:/etc/nginx/conf.d/product.nginx # 配置文件
      - ./public:/public # 静态文件
    ports:
      - 80:80
    links:
      - nest
      - nuxt
    restart: always
    command: nginx -g 'daemon off;' -c /etc/nginx/conf.d/product.nginx


