version: "3"

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: DB_USER
      POSTGRES_PASSWORD: DB_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - ./db_data/:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    command: redis-server --requirepass REDIS_PASSWORD
    ports:
      - 6379:6379
